# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c18311500a6af6f7ab69e40d8cdaba1e0ed962e6fcf7b4ec48f00f1fdae4582de170d8627f67e76de32e028a1125fb18c53b5900649cc1fb6cb3d2d8701b8463

test:
  secret_key_base: ab413e8ba84266aa3efa335e232f9a2d4428da8c9bc020b92a7d1889b39fbe07b1836903d1232161bf486f7bfc11e07125b4c1864988903e44a1b97926e94bf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
